<a href="https://colab.research.google.com/github/IbrahimHammed/DataAnalysis/blob/main/DataAnalysis_005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data cleansing techniques are demonstrated in this notebook**

In [39]:
import pandas as pd
import numpy as np

In [40]:
Student = ['Lola','Lara','Oluchi','Fatimah','Labake','Onyinye','Lateefah','Jennifer','Lisa','Kristin','Laura','Zainab','Ebube','Omotola','Fernanda','Isabella','Anett','Linda','Kashifah','Fatimah']
Gender = ['F','F',np.nan,'F','F',np.nan,np.nan,'F','F','F',np.nan,'F','F','F','F',np.nan,'F','F',np.nan,'F']
Age = [np.nan, 18, np.nan, np.nan, 18, 19, 18, 19, 18, np.nan, np.nan, 19, 18, 17, 18, 17, 19, 20, 19, np.nan]
Biology = [30, 27, 18, np.nan, np.nan, 24, 21, 26, np.nan, 19, 27, 25, np.nan, 20, 21, 19, 28, 22, 19, np.nan]
Chemistry = [24, 16, 19, np.nan, 21, np.nan, 15, 17, 20, np.nan, 18, 19, 21, 17, np.nan, 16, 18, 20, 19, np.nan]
Physics = [23, 21, np.nan, np.nan, 20, np.nan, 26, 24, 19, 21, 27,np.nan, np.nan, 22, 28, 20, np.nan, 18, 24, np.nan]

data = {'Student':Student, 'Gender':Gender, 'Age':Age, 'Biology':Biology, 'Chemistry':Chemistry, 'Physics':Physics}

In [41]:
dfCA = pd.DataFrame(data)
dfCA

     Student Gender   Age  Biology  Chemistry  Physics
0       Lola      F   NaN     30.0       24.0     23.0
1       Lara      F  18.0     27.0       16.0     21.0
2     Oluchi    NaN   NaN     18.0       19.0      NaN
3    Fatimah      F   NaN      NaN        NaN      NaN
4     Labake      F  18.0      NaN       21.0     20.0
5    Onyinye    NaN  19.0     24.0        NaN      NaN
6   Lateefah    NaN  18.0     21.0       15.0     26.0
7   Jennifer      F  19.0     26.0       17.0     24.0
8       Lisa      F  18.0      NaN       20.0     19.0
9    Kristin      F   NaN     19.0        NaN     21.0
10     Laura    NaN   NaN     27.0       18.0     27.0
11    Zainab      F  19.0     25.0       19.0      NaN
12     Ebube      F  18.0      NaN       21.0      NaN
13   Omotola      F  17.0     20.0       17.0     22.0
14  Fernanda      F  18.0     21.0        NaN     28.0
15  Isabella    NaN  17.0     19.0       16.0     20.0
16     Anett      F  19.0     28.0       18.0      NaN
17     Linda      F  20.0     22.0       20.0     18.0
18  Kashifah    NaN  19.0     19.0       19.0     24.0
19   Fatimah      F   NaN      NaN        NaN      NaN

In [43]:
dfCA[dfCA.duplicated()]

    Student Gender  Age  Biology  Chemistry  Physics
19  Fatimah      F  NaN      NaN        NaN      NaN

In [44]:
dfCA.drop_duplicates(inplace=True)
dfCA

     Student Gender   Age  Biology  Chemistry  Physics
0       Lola      F   NaN     30.0       24.0     23.0
1       Lara      F  18.0     27.0       16.0     21.0
2     Oluchi    NaN   NaN     18.0       19.0      NaN
3    Fatimah      F   NaN      NaN        NaN      NaN
4     Labake      F  18.0      NaN       21.0     20.0
5    Onyinye    NaN  19.0     24.0        NaN      NaN
6   Lateefah    NaN  18.0     21.0       15.0     26.0
7   Jennifer      F  19.0     26.0       17.0     24.0
8       Lisa      F  18.0      NaN       20.0     19.0
9    Kristin      F   NaN     19.0        NaN     21.0
10     Laura    NaN   NaN     27.0       18.0     27.0
11    Zainab      F  19.0     25.0       19.0      NaN
12     Ebube      F  18.0      NaN       21.0      NaN
13   Omotola      F  17.0     20.0       17.0     22.0
14  Fernanda      F  18.0     21.0        NaN     28.0
15  Isabella    NaN  17.0     19.0       16.0     20.0
16     Anett      F  19.0     28.0       18.0      NaN
17     Linda      F  20.0     22.0       20.0     18.0
18  Kashifah    NaN  19.0     19.0       19.0     24.0

**Detecting missing values across columns**

In [20]:
# Method-1: info
dfCA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Student    20 non-null     object
 1   Gender     14 non-null     object
 2   Age        14 non-null     float64
 3   Biology    15 non-null     float64
 4   Chemistry  15 non-null     float64
 5   Physics    13 non-null     float64
dtypes: float64(4), object(2)
memory usage: 1.1+ KB

In [22]:
# Method-2: isnull
dfCA.isnull().sum()

Student      0
Gender       6
Age          6
Biology      5
Chemistry    5
Physics      7
dtype: int64

In [23]:
# Method-3: isna
dfCA.isna().sum()

Student      0
Gender       6
Age          6
Biology      5
Chemistry    5
Physics      7
dtype: int64

**Handling missing enties**

In [24]:
# Method-1: Delete records affected
dfNew = dfCA.dropna()
dfNew.shape

(4, 6)

In [25]:
dfNew

     Student Gender   Age  Biology  Chemistry  Physics
1       Lara      F  18.0     27.0       16.0     21.0
7   Jennifer      F  19.0     26.0       17.0     24.0
13   Omotola      F  17.0     20.0       17.0     22.0
17     Linda      F  20.0     22.0       20.0     18.0

In [28]:
# Method-2: Replace with a known text value [for text columns]
# Option-1
dfNew = dfCA.fillna(0, inplace=False)
dfNew

     Student Gender   Age  Biology  Chemistry  Physics
0       Lola      F   0.0     30.0       24.0     23.0
1       Lara      F  18.0     27.0       16.0     21.0
2     Oluchi      0   0.0     18.0       19.0      0.0
3    Fatimah      F   0.0      0.0        0.0      0.0
4     Labake      F  18.0      0.0       21.0     20.0
5    Onyinye      0  19.0     24.0        0.0      0.0
6   Lateefah      0  18.0     21.0       15.0     26.0
7   Jennifer      F  19.0     26.0       17.0     24.0
8       Lisa      F  18.0      0.0       20.0     19.0
9    Kristin      F   0.0     19.0        0.0     21.0
10     Laura      0   0.0     27.0       18.0     27.0
11    Zainab      F  19.0     25.0       19.0      0.0
12     Ebube      F  18.0      0.0       21.0      0.0
13   Omotola      F  17.0     20.0       17.0     22.0
14  Fernanda      F  18.0     21.0        0.0     28.0
15  Isabella      0  17.0     19.0       16.0     20.0
16     Anett      F  19.0     28.0       18.0      0.0
17     Linda      F  20.0     22.0       20.0     18.0
18  Kashifah      0  19.0     19.0       19.0     24.0
19   Fatimah      F   0.0      0.0        0.0      0.0

In [29]:
# Method-2: Replace with a known text value [for text columns]
# Option-2
dfNew = dfCA['Gender'].fillna('F', inplace=False)
dfNew

0     F
1     F
2     F
3     F
4     F
5     F
6     F
7     F
8     F
9     F
10    F
11    F
12    F
13    F
14    F
15    F
16    F
17    F
18    F
19    F
Name: Gender, dtype: object

In [9]:
# Method-3: Replace with a known date value [for date columns]

In [10]:
# Method-4: Replace with zero [for numeric columns]

In [30]:
# Method-5: Replace with mean of the specific column [for numeric columns]
dfCA.head()

   Student Gender   Age  Biology  Chemistry  Physics
0     Lola      F   NaN     30.0       24.0     23.0
1     Lara      F  18.0     27.0       16.0     21.0
2   Oluchi    NaN   NaN     18.0       19.0      NaN
3  Fatimah      F   NaN      NaN        NaN      NaN
4   Labake      F  18.0      NaN       21.0     20.0

In [31]:
arbitraryNumber = dfCA['Age'].mean()
arbitraryNumber

18.357142857142858

In [33]:
dfCA['Age'].fillna(arbitraryNumber, inplace=True)

# Converting Age column from float to int
dfCA['Age'] = dfCA['Age'].astype(int)
dfCA

<ipython-input-33-f3130bc8f602>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfCA['Age'].fillna(arbitraryNumber, inplace=True)

     Student Gender  Age  Biology  Chemistry  Physics
0       Lola      F   18     30.0       24.0     23.0
1       Lara      F   18     27.0       16.0     21.0
2     Oluchi    NaN   18     18.0       19.0      NaN
3    Fatimah      F   18      NaN        NaN      NaN
4     Labake      F   18      NaN       21.0     20.0
5    Onyinye    NaN   19     24.0        NaN      NaN
6   Lateefah    NaN   18     21.0       15.0     26.0
7   Jennifer      F   19     26.0       17.0     24.0
8       Lisa      F   18      NaN       20.0     19.0
9    Kristin      F   18     19.0        NaN     21.0
10     Laura    NaN   18     27.0       18.0     27.0
11    Zainab      F   19     25.0       19.0      NaN
12     Ebube      F   18      NaN       21.0      NaN
13   Omotola      F   17     20.0       17.0     22.0
14  Fernanda      F   18     21.0        NaN     28.0
15  Isabella    NaN   17     19.0       16.0     20.0
16     Anett      F   19     28.0       18.0      NaN
17     Linda      F   20     22.0       20.0     18.0
18  Kashifah    NaN   19     19.0       19.0     24.0
19   Fatimah      F   18      NaN        NaN      NaN

In [34]:
# Method-6: Backfill
dfCA.fillna(method='bfill', inplace=True)
dfCA

<ipython-input-34-6a2764a6d55e>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfCA.fillna(method='bfill', inplace=True)

     Student Gender  Age  Biology  Chemistry  Physics
0       Lola      F   18     30.0       24.0     23.0
1       Lara      F   18     27.0       16.0     21.0
2     Oluchi      F   18     18.0       19.0     20.0
3    Fatimah      F   18     24.0       21.0     20.0
4     Labake      F   18     24.0       21.0     20.0
5    Onyinye      F   19     24.0       15.0     26.0
6   Lateefah      F   18     21.0       15.0     26.0
7   Jennifer      F   19     26.0       17.0     24.0
8       Lisa      F   18     19.0       20.0     19.0
9    Kristin      F   18     19.0       18.0     21.0
10     Laura      F   18     27.0       18.0     27.0
11    Zainab      F   19     25.0       19.0     22.0
12     Ebube      F   18     20.0       21.0     22.0
13   Omotola      F   17     20.0       17.0     22.0
14  Fernanda      F   18     21.0       16.0     28.0
15  Isabella      F   17     19.0       16.0     20.0
16     Anett      F   19     28.0       18.0     18.0
17     Linda      F   20     22.0       20.0     18.0
18  Kashifah      F   19     19.0       19.0     24.0
19   Fatimah      F   18      NaN        NaN      NaN

In [ ]:
# Focusing on a specific column
dfCA['Biology'].fillna(method='bfill', inplace=True)

In [35]:
# Method-7: Forwardfill
dfCA.fillna(method='ffill', inplace=True)
dfCA

<ipython-input-35-a9935dbf78c7>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfCA.fillna(method='ffill', inplace=True)

     Student Gender  Age  Biology  Chemistry  Physics
0       Lola      F   18     30.0       24.0     23.0
1       Lara      F   18     27.0       16.0     21.0
2     Oluchi      F   18     18.0       19.0     20.0
3    Fatimah      F   18     24.0       21.0     20.0
4     Labake      F   18     24.0       21.0     20.0
5    Onyinye      F   19     24.0       15.0     26.0
6   Lateefah      F   18     21.0       15.0     26.0
7   Jennifer      F   19     26.0       17.0     24.0
8       Lisa      F   18     19.0       20.0     19.0
9    Kristin      F   18     19.0       18.0     21.0
10     Laura      F   18     27.0       18.0     27.0
11    Zainab      F   19     25.0       19.0     22.0
12     Ebube      F   18     20.0       21.0     22.0
13   Omotola      F   17     20.0       17.0     22.0
14  Fernanda      F   18     21.0       16.0     28.0
15  Isabella      F   17     19.0       16.0     20.0
16     Anett      F   19     28.0       18.0     18.0
17     Linda      F   20     22.0       20.0     18.0
18  Kashifah      F   19     19.0       19.0     24.0
19   Fatimah      F   18     19.0       19.0     24.0

In [36]:
# Method-8: Interpolate
dfCA.interpolate(method='linear', inplace=True)
dfCA

<ipython-input-36-15e74c7c177b>:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  dfCA.interpolate(method='linear', inplace=True)

     Student Gender  Age  Biology  Chemistry  Physics
0       Lola      F   18     30.0       24.0     23.0
1       Lara      F   18     27.0       16.0     21.0
2     Oluchi      F   18     18.0       19.0     20.0
3    Fatimah      F   18     24.0       21.0     20.0
4     Labake      F   18     24.0       21.0     20.0
5    Onyinye      F   19     24.0       15.0     26.0
6   Lateefah      F   18     21.0       15.0     26.0
7   Jennifer      F   19     26.0       17.0     24.0
8       Lisa      F   18     19.0       20.0     19.0
9    Kristin      F   18     19.0       18.0     21.0
10     Laura      F   18     27.0       18.0     27.0
11    Zainab      F   19     25.0       19.0     22.0
12     Ebube      F   18     20.0       21.0     22.0
13   Omotola      F   17     20.0       17.0     22.0
14  Fernanda      F   18     21.0       16.0     28.0
15  Isabella      F   17     19.0       16.0     20.0
16     Anett      F   19     28.0       18.0     18.0
17     Linda      F   20     22.0       20.0     18.0
18  Kashifah      F   19     19.0       19.0     24.0
19   Fatimah      F   18     19.0       19.0     24.0

**Handling duplicates**

In [37]:
dfCA.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

Assignment: Make an attempt to load and clean the file below using the techniques above: https://github.com/IbrahimHammed/DataAnalysis/blob/main/landslides.csv

In [46]:
url = "https://github.com/IbrahimHammed/DataAnalysis/blob/main/landslides.csv?raw=true"
df = pd.read_csv(url)
df.sample(14)

,id,date,time,country_name,state/province,population,landslide_type,trigger,fatalities
463,2521,9/29/10,NaN,Mexico,Chiapas,1088,Complex,Tropical cyclone,3.0
843,4082,12/2/11,NaN,Trinidad and Tobago,Couva-Tabaquite-Talparo,3314,Mudslide,Downpour,0.0
427,2349,8/28/10,NaN,Guatemala,Guatemala,473080,Landslide,Downpour,0.0
581,3021,1/16/11,NaN,United States,Idaho,145987,Mudslide,Downpour,0.0
43,299,10/9/07,NaN,Costa Rica,San José,3072,Complex,Rain,4.0
1392,6705,6/24/14,NaN,Panama,Panamá,9169,Landslide,Unknown,0.0
38,250,9/9/07,NaN,Dominica,Saint George,16571,Landslide,Rain,NaN
230,1353,12/9/09,NaN,United States,Tennessee,167674,Mudslide,Downpour,0.0
1314,6382,11/9/14,NaN,United States,Ohio,49138,Landslide,Construction,0.0
747,3563,6/2/11,NaN,Haiti,Sud-Est,137966,Landslide,Downpour,0.0
459,2517,9/29/10,NaN,Jamaica,Saint Mary,2046,Landslide,Downpour,0.0
105,577,6/7/08,NaN,United States,Indiana,11828,Mudslide,Downpour,NaN
845,4085,12/4/11,3:00:00,Trinidad and Tobago,Sangre Grande,15968,Mudslide,Downpour,1.0
1462,6952,6/18/15,NaN,United States,Oklahoma,2739,Mudslide,Continuous rain,0.0

In [47]:
df.isnull().sum()

id                   0
date                 3
time              1064
country_name         0
state/province       1
population           0
landslide_type       1
trigger              2
fatalities         247
dtype: int64

In [48]:
df.shape

(1693, 9)