<a href="https://colab.research.google.com/github/IbrahimHammed/DataAnalysis/blob/main/DataAnalysis_007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np

In [38]:
# This generates 100 date entries starting from 1/1/2000 with difference of 30 days
dateVals = pd.period_range('1/1/2000', freq='30d', periods=100)

In [39]:
dateVals

PeriodIndex(['2000-01-01', '2000-01-31', '2000-03-01', '2000-03-31',
             '2000-04-30', '2000-05-30', '2000-06-29', '2000-07-29',
             '2000-08-28', '2000-09-27', '2000-10-27', '2000-11-26',
             '2000-12-26', '2001-01-25', '2001-02-24', '2001-03-26',
             '2001-04-25', '2001-05-25', '2001-06-24', '2001-07-24',
             '2001-08-23', '2001-09-22', '2001-10-22', '2001-11-21',
             '2001-12-21', '2002-01-20', '2002-02-19', '2002-03-21',
             '2002-04-20', '2002-05-20', '2002-06-19', '2002-07-19',
             '2002-08-18', '2002-09-17', '2002-10-17', '2002-11-16',
             '2002-12-16', '2003-01-15', '2003-02-14', '2003-03-16',
             '2003-04-15', '2003-05-15', '2003-06-14', '2003-07-14',
             '2003-08-13', '2003-09-12', '2003-10-12', '2003-11-11',
             '2003-12-11', '2004-01-10', '2004-02-09', '2004-03-10',
             '2004-04-09', '2004-05-09', '2004-06-08', '2004-07-08',
             '2004-08-07', '2004-09-06', '2004-10-06', '2004-11-05',
             '2004-12-05', '2005-01-04', '2005-02-03', '2005-03-05',
             '2005-04-04', '2005-05-04', '2005-06-03', '2005-07-03',
             '2005-08-02', '2005-09-01', '2005-10-01', '2005-10-31',
             '2005-11-30', '2005-12-30', '2006-01-29', '2006-02-28',
             '2006-03-30', '2006-04-29', '2006-05-29', '2006-06-28',
             '2006-07-28', '2006-08-27', '2006-09-26', '2006-10-26',
             '2006-11-25', '2006-12-25', '2007-01-24', '2007-02-23',
             '2007-03-25', '2007-04-24', '2007-05-24', '2007-06-23',
             '2007-07-23', '2007-08-22', '2007-09-21', '2007-10-21',
             '2007-11-20', '2007-12-20', '2008-01-19', '2008-02-18'],
            dtype='period[30D]')

In [40]:
# This generates 100 random integers between 100,000 and 1,000,000
salesVals = np.random.randint(100000, 1000000, len(dateVals))

In [66]:
_sales_vals = np.random.randint(100000, 1000000, len(dateVals))

In [67]:
SalesValue = np.random.randint(100000, 1000000, len(dateVals))

In [68]:
salesValues = np.random.randint(100000, 1000000, len(dateVals))

In [69]:
# sv stands for sales value
sv = np.random.randint(100000, 1000000, len(dateVals))

In [41]:
salesVals

array([505699, 283191, 372586, 948739, 526377, 140352, 113797, 383343,
       247665, 722234, 605465, 857337, 812311, 403374, 521081, 830620,
       488429, 584554, 308755, 926875, 130031, 170722, 250355, 257808,
       877286, 504755, 371351, 646013, 996530, 769776, 330961, 533691,
       703515, 387757, 221071, 713253, 231126, 528003, 807815, 492795,
       420510, 784917, 713106, 706450, 895389, 841374, 403356, 464441,
       918829, 672612, 280329, 583136, 657753, 723895, 327608, 301748,
       624463, 735854, 707323, 475836, 292088, 787710, 269944, 979464,
       162613, 680319, 846547, 485685, 243946, 829598, 389971, 410961,
       177235, 985908, 794521, 132469, 350343, 383840, 261883, 575423,
       282866, 458241, 821532, 482186, 745835, 596714, 147463, 188122,
       577269, 710466, 865972, 551661, 860770, 184961, 195428, 151944,
       548865, 528269, 608608, 463217])

In [42]:
# Form data frame
dfSalesData = pd.DataFrame({'Date': dateVals, 'Sales': salesVals})
dfSalesData.sample(10)

          Date   Sales
42  2003-06-14  713106
17  2001-05-25  584554
20  2001-08-23  130031
5   2000-05-30  140352
70  2005-10-01  389971
98  2008-01-19  608608
0   2000-01-01  505699
31  2002-07-19  533691
19  2001-07-24  926875
99  2008-02-18  463217

In [43]:
# Total Sales
dfSalesData["Sales"].sum()

52757184

In [44]:
# Average Sales
dfSalesData["Sales"].mean()

527571.84

In [45]:
# Highest Sales
dfSalesData["Sales"].max()

996530

In [46]:
# Minimum Sales
dfSalesData["Sales"].min()

113797

In [47]:
# Transaction count
dfSalesData["Sales"].count()

100

In [48]:
# Preview the dataframe
dfSalesData.head()

         Date   Sales
0  2000-01-01  505699
1  2000-01-31  283191
2  2000-03-01  372586
3  2000-03-31  948739
4  2000-04-30  526377

In [49]:
# This does cummulative sum of the sales figures
dfSalesData["CummulativeSales"] = dfSalesData["Sales"].cumsum()
dfSalesData.head(10)

         Date   Sales  CummulativeSales
0  2000-01-01  505699            505699
1  2000-01-31  283191            788890
2  2000-03-01  372586           1161476
3  2000-03-31  948739           2110215
4  2000-04-30  526377           2636592
5  2000-05-30  140352           2776944
6  2000-06-29  113797           2890741
7  2000-07-29  383343           3274084
8  2000-08-28  247665           3521749
9  2000-09-27  722234           4243983

In [50]:
# This demonstrates how to do 2 month-moving average with Python
MA = 2
dfSalesData["Sales2MA"] = dfSalesData["Sales"].rolling(window=MA).mean()
dfSalesData.head(10)

         Date   Sales  CummulativeSales  Sales2MA
0  2000-01-01  505699            505699       NaN
1  2000-01-31  283191            788890  394445.0
2  2000-03-01  372586           1161476  327888.5
3  2000-03-31  948739           2110215  660662.5
4  2000-04-30  526377           2636592  737558.0
5  2000-05-30  140352           2776944  333364.5
6  2000-06-29  113797           2890741  127074.5
7  2000-07-29  383343           3274084  248570.0
8  2000-08-28  247665           3521749  315504.0
9  2000-09-27  722234           4243983  484949.5

In [51]:
# This demonstrates how to do 3 month-moving average with Python
MA = 3
dfSalesData["Sales3MA"] = dfSalesData["Sales"].rolling(window=MA).mean()
dfSalesData.head(10)

         Date   Sales  CummulativeSales  Sales2MA       Sales3MA
0  2000-01-01  505699            505699       NaN            NaN
1  2000-01-31  283191            788890  394445.0            NaN
2  2000-03-01  372586           1161476  327888.5  387158.666667
3  2000-03-31  948739           2110215  660662.5  534838.666667
4  2000-04-30  526377           2636592  737558.0  615900.666667
5  2000-05-30  140352           2776944  333364.5  538489.333333
6  2000-06-29  113797           2890741  127074.5  260175.333333
7  2000-07-29  383343           3274084  248570.0  212497.333333
8  2000-08-28  247665           3521749  315504.0  248268.333333
9  2000-09-27  722234           4243983  484949.5  451080.666667

In [52]:
# This gives date diff along the column
dfSalesData["SalesDateDiff"] = dfSalesData["Date"].diff(periods=1)
dfSalesData.head()

         Date   Sales  CummulativeSales  Sales2MA       Sales3MA SalesDateDiff
0  2000-01-01  505699            505699       NaN            NaN           NaT
1  2000-01-31  283191            788890  394445.0            NaN   <30 * Days>
2  2000-03-01  372586           1161476  327888.5  387158.666667   <30 * Days>
3  2000-03-31  948739           2110215  660662.5  534838.666667   <30 * Days>
4  2000-04-30  526377           2636592  737558.0  615900.666667   <30 * Days>

In [53]:
# Gives the first day for whichever date is processed
dfSalesData["MonthFirstDay"] = dfSalesData["Date"].values.astype('datetime64[M]')
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01

In [54]:
# Shows data types of different columns
dfSalesData.dtypes

Date                  period[30D]
Sales                       int64
CummulativeSales            int64
Sales2MA                  float64
Sales3MA                  float64
SalesDateDiff              object
MonthFirstDay       datetime64[s]
dtype: object

In [55]:
# Changes the data type of the sales column in preparation for next set of analysis
dfSalesData["Date"] = dfSalesData["Date"].dt.to_timestamp()
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01

In [56]:
# Deducts date x from date y
dfSalesData["Duration"] = dfSalesData['Date'] - dfSalesData['MonthFirstDay']
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days

In [57]:
# Deducts 4 days from sales date column
dfSalesData["DateMinus4"] = dfSalesData["Date"] - pd.Timedelta(days=4)
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26

In [58]:
# Deducts 4 days from sales date column
dfSalesData["DateMinus4B"] = dfSalesData["Date"] + pd.Timedelta(days=-4)
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26

In [59]:
# Extracts the day part of sales date
dfSalesData["SalesDay"] = dfSalesData["Date"].dt.day
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30

In [60]:
# Extracts the day name part of sales date
dfSalesData["SalesDayName"] = dfSalesData["Date"].dt.day_name()
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay,SalesDayName
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1,Saturday
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31,Monday
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1,Wednesday
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31,Friday
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30,Sunday

In [61]:
# Extracts the month number part of sales date
dfSalesData["SalesDayMonth"] = dfSalesData["Date"].dt.month
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay,SalesDayName,SalesDayMonth
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1,Saturday,1
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31,Monday,1
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1,Wednesday,3
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31,Friday,3
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30,Sunday,4

In [62]:
# Extracts the month name part of sales date
dfSalesData["SalesDayMonthName"] = dfSalesData["Date"].dt.month_name()
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay,SalesDayName,SalesDayMonth,SalesDayMonthName
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1,Saturday,1,January
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31,Monday,1,January
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1,Wednesday,3,March
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31,Friday,3,March
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30,Sunday,4,April

In [63]:
# Extracts the quarter number of sales date
dfSalesData["SalesQuarter"] = dfSalesData["Date"].dt.quarter
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay,SalesDayName,SalesDayMonth,SalesDayMonthName,SalesQuarter
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1,Saturday,1,January,1
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31,Monday,1,January,1
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1,Wednesday,3,March,1
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31,Friday,3,March,1
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30,Sunday,4,April,2

In [64]:
# Extracts the quarter part of sales date in the form of Q1
dfSalesData["SalesQuarterName"] = "Q" + dfSalesData["SalesQuarter"].astype(str)
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay,SalesDayName,SalesDayMonth,SalesDayMonthName,SalesQuarter,SalesQuarterName
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1,Saturday,1,January,1,Q1
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31,Monday,1,January,1,Q1
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1,Wednesday,3,March,1,Q1
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31,Friday,3,March,1,Q1
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30,Sunday,4,April,2,Q2

In [65]:
# Extracts the year part of sales date
dfSalesData["SalesYear"] = dfSalesData["Date"].dt.year
dfSalesData.head()

,Date,Sales,CummulativeSales,Sales2MA,Sales3MA,SalesDateDiff,MonthFirstDay,Duration,DateMinus4,DateMinus4B,SalesDay,SalesDayName,SalesDayMonth,SalesDayMonthName,SalesQuarter,SalesQuarterName,SalesYear
0,2000-01-01,505699,505699,NaN,NaN,NaT,2000-01-01,0 days,1999-12-28,1999-12-28,1,Saturday,1,January,1,Q1,2000
1,2000-01-31,283191,788890,394445.0,NaN,<30 * Days>,2000-01-01,30 days,2000-01-27,2000-01-27,31,Monday,1,January,1,Q1,2000
2,2000-03-01,372586,1161476,327888.5,387158.666667,<30 * Days>,2000-03-01,0 days,2000-02-26,2000-02-26,1,Wednesday,3,March,1,Q1,2000
3,2000-03-31,948739,2110215,660662.5,534838.666667,<30 * Days>,2000-03-01,30 days,2000-03-27,2000-03-27,31,Friday,3,March,1,Q1,2000
4,2000-04-30,526377,2636592,737558.0,615900.666667,<30 * Days>,2000-04-01,29 days,2000-04-26,2000-04-26,30,Sunday,4,April,2,Q2,2000